# Generated by Django 5.2 on 2025-04-23 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('CE', 'Cyber Essentials'), ('CE+', 'Cyber Essentials Plus')], max_length=3)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scoping_Client', 'Scoping (Client Input)'), ('Scoping_Review', 'Scoping (Assessor Review)'), ('Testing', 'Testing'), ('Remediation', 'Remediation'), ('Report_Pending', 'Report Pending'), ('Complete_Passed', 'Complete (Passed)'), ('Complete_Failed', 'Complete (Failed)')], default='Draft', max_length=20)),
                ('scope_description', models.TextField(blank=True, help_text='Brief description of the scope boundary.')),
                ('scope_type', models.CharField(choices=[('Whole_Org', 'Whole Organisation'), ('Sub_Set', 'Sub-Set')], default='Whole_Org', max_length=10)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_target_end', models.DateField(blank=True, null=True, verbose_name='Target End Date')),
                ('date_actual_end', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('date_cert_issued', models.DateField(blank=True, null=True, verbose_name='Certificate Issued Date')),
                ('date_cert_expiry', models.DateField(blank=True, null=True, verbose_name='Certificate Expiry Date')),
                ('ce_self_assessment_ref', models.CharField(blank=True, max_length=100, verbose_name='CE Self-Assessment Ref')),
                ('final_outcome', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'Assessor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='tracker.client')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.assessment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('description', models.CharField(help_text='E.g., Final Report, Certificate', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='tracker.assessment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScopedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Server', 'Server'), ('Mobile', 'Mobile Device'), ('IP', 'Network Device (IP)'), ('SaaS', 'Software as a Service'), ('PaaS', 'Platform as a Service'), ('IaaS', 'Infrastructure as a Service'), ('Firewall', 'Firewall'), ('Router', 'Router'), ('Switch', 'Switch'), ('Other', 'Other')], max_length=10)),
                ('identifier', models.CharField(help_text='E.g., Hostname, IP Address, Service Name', max_length=200)),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='OS/Version')),
                ('make_model', models.CharField(blank=True, max_length=100, verbose_name='Make/Model')),
                ('role_function', models.TextField(blank=True, help_text='Purpose within the business.')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, choices=[('Organisation', 'Organisation Owned'), ('BYOD', 'Bring Your Own Device')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_items', to='tracker.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Assessor', 'Assessor'), ('Client', 'Client')], max_length=10)),
                ('client', models.ForeignKey(blank=True, help_text="Required only if role is 'Client'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
