# Generated by Django 5.2 on 2025-04-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopeditem',
            name='os_version',
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Windows 11 Pro, macOS, Ubuntu Linux', max_length=100)),
                ('version', models.CharField(blank=True, help_text='E.g., 23H2, Sonoma 14.4, 22.04 LTS', max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('vendor_website', models.URLField(blank=True, max_length=255, verbose_name='Vendor Website')),
                ('end_of_life_date', models.DateField(blank=True, help_text='Approximate End-of-Life or End-of-Support date', null=True)),
                ('is_supported', models.BooleanField(default=True, help_text='Is this OS version currently supported?')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['vendor', 'name', 'version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='scopeditem',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_items', to='tracker.operatingsystem', verbose_name='Operating System / Version'),
        ),
    ]
