# Generated by Django 5.2 on 2025-04-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_scopeditem_os_version_operatingsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeditem',
            name='identifier',
            field=models.CharField(blank=True, help_text='E.g., Hostname, Asset Tag (Can be added/edited later if creating multiple)', max_length=200, null=True),
        ),
    ]
