# Generated by Django 5.2 on 2025-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_scopeditem_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeditem',
            name='is_in_ce_plus_sample',
            field=models.BooleanField(default=False, help_text='Marked by assessor as part of the CE+ test sample.', verbose_name='In CE+ Sample'),
        ),
    ]
