# Generated by Django 5.2 on 2025-04-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_scopeditem_is_in_ce_plus_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Office LAN', 'Guest WiFi', 'Azure Production VNet'", max_length=150)),
                ('description', models.TextField(blank=True, help_text="Optional description of the network's purpose or location.")),
                ('ip_range', models.CharField(blank=True, help_text='e.g., 192.168.1.0/24, 10.0.0.0/8', max_length=100, verbose_name='IP Range / Subnet')),
                ('vlan_id', models.IntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='tracker.assessment')),
            ],
            options={
                'ordering': ['assessment', 'name'],
                'unique_together': {('assessment', 'name')},
            },
        ),
        migrations.AddField(
            model_name='scopeditem',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_items', to='tracker.network', verbose_name='Associated Network'),
        ),
    ]
