# Generated by Django 5.2 on 2025-04-25 21:16

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_network_scopeditem_network'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the cloud service (e.g., Microsoft 365 Business Premium)', max_length=200, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('service_url', models.URLField(blank=True, max_length=255, verbose_name='Service Login/Info URL')),
                ('description', models.TextField(blank=True, help_text='Brief description of the service.')),
                ('requires_mfa_for_ce', models.BooleanField(default=True, help_text='Does Cyber Essentials mandate MFA for this type of service?', verbose_name='MFA Required for CE')),
                ('is_globally_approved', models.BooleanField(default=False, help_text='Approved by Admin/Assessor for selection by clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cloud_services', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_cloud_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Service Definition',
                'verbose_name_plural': 'Cloud Service Definitions',
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCloudService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_notes', models.TextField(blank=True, verbose_name='Client Usage Notes')),
                ('mfa_admin_proof', models.FileField(blank=True, null=True, upload_to=tracker.models.mfa_proof_upload_path, verbose_name='Admin MFA Proof')),
                ('mfa_user_proof', models.FileField(blank=True, null=True, upload_to=tracker.models.mfa_proof_upload_path, verbose_name='User MFA Proof')),
                ('mfa_admin_verified', models.BooleanField(default=False, verbose_name='Admin MFA Verified')),
                ('mfa_user_verified', models.BooleanField(default=False, verbose_name='User MFA Verified')),
                ('is_compliant', models.BooleanField(default=False, verbose_name='MFA Compliant')),
                ('assessor_notes', models.TextField(blank=True, verbose_name='Assessor Verification Notes')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_cloud_services', to='tracker.assessment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cloud_services', to=settings.AUTH_USER_MODEL)),
                ('cloud_service_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_instances', to='tracker.cloudservicedefinition', verbose_name='Cloud Service')),
            ],
            options={
                'verbose_name': 'Assessment Cloud Service',
                'verbose_name_plural': 'Assessment Cloud Services',
                'ordering': ['assessment', 'cloud_service_definition__name'],
                'unique_together': {('assessment', 'cloud_service_definition')},
            },
        ),
    ]
