# Generated by Django 5.2 on 2025-04-26 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_cloudservicedefinition_assessmentcloudservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='Order in which the step appears.', unique=True)),
                ('name', models.CharField(help_text='Short name/identifier for the step.', max_length=100)),
                ('description', models.TextField(help_text='Full description of the step requirement.')),
                ('assignee_type', models.CharField(choices=[('Applicant', 'Applicant'), ('Assessor', 'Assessor'), ('Both', 'Both')], default='Both', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this step currently part of the standard workflow?')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NotStarted', 'Not Started'), ('InProgress', 'In Progress'), ('Complete', 'Complete'), ('Skipped', 'Skipped / Not Applicable')], default='NotStarted', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes specific to this step for this assessment.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='tracker.assessment')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('step_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_steps', to='tracker.workflowstepdefinition')),
            ],
            options={
                'ordering': ['assessment', 'step_definition__step_order'],
                'unique_together': {('assessment', 'step_definition')},
            },
        ),
    ]
