# Generated by Django 5.2 on 2025-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_workflowstepdefinition_assessmentworkflowstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentworkflowstep',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('InProgress', 'In Progress'), ('Complete', 'Complete'), ('HelpNeeded', 'Help Needed'), ('Skipped', 'Skipped / Not Applicable')], default='NotStarted', max_length=20),
        ),
    ]
