# Generated by Django 5.2 on 2025-04-26 20:39

import django.db.models.deletion
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_assessmentworkflowstep_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address_or_hostname', models.CharField(help_text='Enter a valid IPv4, IPv6 address, or a resolvable hostname.', max_length=255, validators=[tracker.models.validate_ip_or_hostname], verbose_name='IP Address or Hostname')),
                ('description', models.TextField(blank=True, help_text="Optional description (e.g., 'Primary Web Server', 'Mail Gateway', 'Client VPN Endpoint').")),
                ('scan_status', models.CharField(blank=True, choices=[('Pending', 'Pending Scan'), ('ScannedOK', 'Scanned - OK'), ('ScannedIssues', 'Scanned - Issues Found'), ('Remediated', 'Issues Remediated'), ('Excluded', 'Excluded from Scan')], default='Pending', max_length=20)),
                ('assessor_notes', models.TextField(blank=True, help_text='Notes regarding scan results or remediation for this IP/hostname.', verbose_name='Assessor Scan Notes')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ips', to='tracker.assessment')),
            ],
            options={
                'verbose_name': 'External IP / Hostname',
                'verbose_name_plural': 'External IPs / Hostnames',
                'ordering': ['assessment', 'ip_address_or_hostname'],
                'unique_together': {('assessment', 'ip_address_or_hostname')},
            },
        ),
    ]
