# Generated by Django 5.2 on 2025-04-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_externalip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalip',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Indicates if explicit consent was provided to scan this target.', verbose_name='Consent to Scan Provided'),
        ),
        migrations.AddField(
            model_name='externalip',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consent Timestamp'),
        ),
        migrations.AddField(
            model_name='externalip',
            name='consented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consented_external_ips', to=settings.AUTH_USER_MODEL, verbose_name='Consented By User'),
        ),
    ]
