# Generated by Django 5.2 on 2025-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_externalip_consent_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='category',
            field=models.CharField(blank=True, choices=[('Desktop', 'Desktop (Windows, macOS, Linux)'), ('Server', 'Server (Windows Server, Linux Server, ESXi)'), ('Mobile', 'Mobile (iOS, Android)'), ('Other', 'Other/Appliance')], help_text='General category this OS applies to (used for form filtering).', max_length=10, null=True),
        ),
    ]
