# Generated by Django 5.2 on 2025-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_uploadedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='companies_house_validated',
            field=models.BooleanField(default=False, help_text='Indicates if details were successfully validated against Companies House.', verbose_name='Companies House Validated'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_companies_house_validation',
            field=models.DateTimeField(blank=True, help_text='When the details were last successfully validated.', null=True, verbose_name='Last Validation Timestamp'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization_number',
            field=models.CharField(blank=True, help_text='Optional: UK Companies House registration number.', max_length=20, null=True, verbose_name='UK Companies House Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='validated_name',
            field=models.CharField(blank=True, editable=False, help_text='Internal: Name used for last validation.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='validated_number',
            field=models.CharField(blank=True, editable=False, help_text='Internal: Number used for last validation.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website_address',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website Address'),
        ),
    ]
