# Generated by Django 5.2 on 2025-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_client_companies_house_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tenable_tag_uuid',
            field=models.CharField(blank=True, help_text="Tenable.io Tag Value UUID for this client's assets", max_length=36, null=True, verbose_name='Tenable Tag UUID'),
        ),
    ]
