# Generated by Django 5.2 on 2025-04-28 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_client_tenable_tag_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NessusAgentURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(help_text='e.g., Windows, Debian, CentOS, macOS', max_length=50)),
                ('architecture', models.CharField(help_text='e.g., x64, amd64, arm64', max_length=20)),
                ('os_version_details', models.CharField(blank=True, help_text='e.g., 10 / 11, 11 / 12, 7 / 8 / 9', max_length=100)),
                ('agent_version', models.CharField(blank=True, help_text='e.g., 10.7.1', max_length=30)),
                ('download_url', models.URLField(max_length=1024, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('last_scraped', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nessus Agent Download URL',
                'verbose_name_plural': 'Nessus Agent Download URLs',
                'ordering': ['os_name', 'architecture', '-agent_version'],
                'indexes': [models.Index(fields=['os_name', 'architecture'], name='tracker_nes_os_name_f554d5_idx')],
            },
        ),
    ]
