# Generated by Django 5.2 on 2025-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_nessusagenturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeditem',
            name='linked_tenable_agent_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the Tenable Nessus Agent linked to this item (if applicable)', null=True),
        ),
    ]
