# Generated by Django 5.2 on 2025-04-30 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_scopeditem_linked_tenable_agent_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date_ce_passed',
            field=models.DateField(blank=True, help_text='Date the basic Cyber Essentials self-assessment was passed (for CE+ window).', null=True, verbose_name='CE Self-Assessment Pass Date'),
        ),
        migrations.CreateModel(
            name='AssessmentDateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField()),
                ('status', models.CharField(choices=[('Suggested', 'Suggested'), ('ClientPreferred', 'Client Preferred'), ('Confirmed', 'Confirmed by Assessor'), ('Rejected', 'Rejected')], default='Suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_options', to='tracker.assessment')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Date Option',
                'verbose_name_plural': 'Assessment Date Options',
                'ordering': ['assessment', 'proposed_date'],
                'unique_together': {('assessment', 'proposed_date')},
            },
        ),
        migrations.CreateModel(
            name='AssessorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailable_date', models.DateField(verbose_name='Date Unavailable')),
                ('reason', models.CharField(blank=True, help_text='Optional reason (e.g., Holiday, Training)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(limit_choices_to={'userprofile__role': 'Assessor'}, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessor Unavailable Date',
                'verbose_name_plural': 'Assessor Unavailable Dates',
                'ordering': ['assessor', 'unavailable_date'],
                'unique_together': {('assessor', 'unavailable_date')},
            },
        ),
    ]
