# Generated by Django 5.2 on 2025-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_assessment_date_ce_passed_assessmentdateoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='tenable_scan_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the last launched Tenable scan for this assessment', null=True, verbose_name='Tenable Scan UUID'),
        ),
    ]
