# Generated by Django 5.2 on 2025-05-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_assessment_tenable_scan_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tenable_agent_group_id',
            field=models.IntegerField(blank=True, help_text='Numeric ID of the corresponding agent group in Tenable.io', null=True),
        ),
    ]
