# Generated by Django 5.2 on 2025-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_client_tenable_agent_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tenable_agent_group_uuid',
            field=models.CharField(blank=True, help_text='UUID (string) of the Tenable.io agent group, fetched from Tenable.io based on the Agent Group ID.', max_length=36, null=True, verbose_name='Tenable Agent Group UUID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tenable_agent_group_id',
            field=models.IntegerField(blank=True, help_text='Integer ID of the Tenable.io agent group for this client.', null=True, verbose_name='Tenable Agent Group ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tenable_tag_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the tag in Tenable.io used to identify assets for this client.', null=True, verbose_name='Tenable Tag UUID'),
        ),
    ]
