# Generated by Django 5.2 on 2025-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_client_tenable_agent_group_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tenable_agent_group_target_name',
            field=models.CharField(blank=True, help_text="The exact name of the Tenable.io Agent Group to use for this client's scans (e.g., 'TEST WE').", max_length=255, null=True),
        ),
    ]
