# Generated by Django 5.2 on 2025-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_client_tenable_agent_group_target_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='scan_status',
            field=models.CharField(choices=[('none', 'Not Scanned'), ('pending_launch', 'Scan Pending Launch'), ('launched', 'Scan Launched'), ('completed', 'Scan Completed by Tenable'), ('processing', 'Processing Results'), ('imported', 'Scan Results Imported'), ('error', 'Error During Scan Operations'), ('timeout', 'Scan Operation Timed Out')], default='none', max_length=30, verbose_name='Tenable Scan Status'),
        ),
    ]
