# Generated by Django 5.2 on 2025-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_assessment_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='scan_status_message',
            field=models.TextField(blank=True, null=True, verbose_name='Scan Status Message'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tenable_scan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tenable Scan Integer ID'),
        ),
    ]
