# Generated by Django 5.2 on 2025-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_assessment_scan_status_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Enable Multi-Factor Authentication for your account.', verbose_name='MFA Enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional: Your contact phone number.', max_length=20, verbose_name='Phone Number'),
        ),
    ]
