# Generated by Django 5.2 on 2025-05-10 15:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_criticalerrorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticalerrorlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Critical Error Log', 'verbose_name_plural': 'Critical Error Logs'},
        ),
        migrations.RemoveField(
            model_name='criticalerrorlog',
            name='funcName',
        ),
        migrations.RemoveField(
            model_name='criticalerrorlog',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='criticalerrorlog',
            name='level_name',
        ),
        migrations.RemoveField(
            model_name='criticalerrorlog',
            name='lineno',
        ),
        migrations.RemoveField(
            model_name='criticalerrorlog',
            name='pathname',
        ),
        migrations.RemoveField(
            model_name='criticalerrorlog',
            name='traceback_info',
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_critical_errors', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By'),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='is_acknowledged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='level',
            field=models.CharField(default='CRITICAL', max_length=50),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criticalerrorlog',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criticalerrorlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='criticalerrorlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='criticalerrorlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
