# Generated by Django 5.2 on 2025-05-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_alter_criticalerrorlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to='tracker.userprofile'),
        ),
    ]
