# Generated by Django 5.2 on 2025-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_client_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='skippable',
            field=models.BooleanField(default=False, help_text='Can this step be skipped by the assignee?'),
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='template_name',
            field=models.CharField(blank=True, help_text="e.g., 'step_contact_details.html' or 'info_step.html'", max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowstepdefinition',
            name='assignee_type',
            field=models.CharField(choices=[('Applicant', 'Applicant (Client)'), ('Assessor', 'Assessor (Internal Staff)'), ('Both', 'Both (Client and Assessor)')], default='Both', max_length=10),
        ),
    ]
