# Generated by Django 5.2 on 2025-05-16 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_workflowstepdefinition_skippable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenableScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_uuid', models.UUIDField(help_text='The UUID of the scan in Tenable.io', verbose_name='Tenable Scan UUID')),
                ('scan_name', models.CharField(blank=True, help_text="A descriptive name for the scan (e.g., 'Initial External Scan', 'Agent Scan - Server X')", max_length=255, null=True, verbose_name='Scan Name')),
                ('status_from_tenable', models.CharField(blank=True, help_text='The status of the scan as reported by Tenable (e.g., completed, aborted, running)', max_length=50, null=True, verbose_name='Status (from Tenable)')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, help_text='When this scan log entry was created (approximates scan launch time)', verbose_name='Log Creation Time')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Scan Completion Time (from Tenable)')),
                ('assets_scanned', models.IntegerField(blank=True, null=True, verbose_name='Number of Assets Scanned')),
                ('critical_vuls', models.IntegerField(blank=True, null=True, verbose_name='Critical Vulnerabilities')),
                ('high_vuls', models.IntegerField(blank=True, null=True, verbose_name='High Vulnerabilities')),
                ('medium_vuls', models.IntegerField(blank=True, null=True, verbose_name='Medium Vulnerabilities')),
                ('low_vuls', models.IntegerField(blank=True, null=True, verbose_name='Low Vulnerabilities')),
                ('raw_summary_data', models.JSONField(blank=True, help_text='Stores the summary JSON object from Tenable for this scan', null=True, verbose_name='Raw Summary Data from Tenable')),
                ('last_fetched_from_tenable', models.DateTimeField(blank=True, null=True, verbose_name='Data Last Fetched From Tenable')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='tracker.assessment', verbose_name='Associated Assessment')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_scans', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
            ],
            options={
                'verbose_name': 'Tenable Scan Log Entry',
                'verbose_name_plural': 'Tenable Scan Log Entries',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
