# Generated by Django 5.2 on 2025-05-16 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_tenablescanlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenablescanlog',
            options={'ordering': ['-initiated_at'], 'verbose_name': 'Tenable Scan Log', 'verbose_name_plural': 'Tenable Scan Logs'},
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='assets_scanned',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='critical_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='high_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='last_fetched_from_tenable',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='low_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='medium_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='raw_summary_data',
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='last_status_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='scan_run_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the specific scan instance/run from Tenable', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='tenable_scan_id',
            field=models.CharField(blank=True, help_text='Numeric ID of the scan definition in Tenable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenable_scan_logs', to='tracker.assessment'),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='initiated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='scan_name',
            field=models.CharField(blank=True, help_text='Name of the scan definition in Tenable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='scan_uuid',
            field=models.UUIDField(help_text='UUID of the scan definition in Tenable'),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='status_from_tenable',
            field=models.CharField(blank=True, help_text='Status reported by Tenable API for this scan run', max_length=100, null=True),
        ),
    ]
