# Generated by Django 5.2 on 2025-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_alter_tenablescanlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='last_status_check',
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='assets_scanned',
            field=models.IntegerField(blank=True, help_text='Number of assets scanned', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='critical_vuls',
            field=models.IntegerField(blank=True, help_text='Number of critical vulnerabilities found', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='high_vuls',
            field=models.IntegerField(blank=True, help_text='Number of high vulnerabilities found', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='last_fetched_from_tenable',
            field=models.DateTimeField(blank=True, help_text='When the scan results were last fetched/updated from Tenable', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='low_vuls',
            field=models.IntegerField(blank=True, help_text='Number of low vulnerabilities found', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='medium_vuls',
            field=models.IntegerField(blank=True, help_text='Number of medium vulnerabilities found', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='raw_summary_data',
            field=models.JSONField(blank=True, help_text="Raw JSON summary data from Tenable for this scan run's results", null=True),
        ),
    ]
