# Generated by Django 5.2 on 2025-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_remove_tenablescanlog_last_status_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='last_tenable_scan_launch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Tenable Scan Launch Time'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='tenable_scan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tenable Scan Definition Numeric ID'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='tenable_scan_uuid',
            field=models.CharField(blank=True, help_text="Identifier of the Tenable scan definition (can be prefixed like 'template-...')", max_length=255, null=True, verbose_name='Tenable Scan Definition UUID/Identifier'),
        ),
    ]
