# Generated by Django 5.2 on 2025-05-16 20:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_assessment_last_tenable_scan_launch_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenablescanlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tenable Scan Log', 'verbose_name_plural': 'Tenable Scan Logs'},
        ),
        migrations.RenameField(
            model_name='tenablescanlog',
            old_name='initiated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='assets_scanned',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='critical_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='high_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='last_fetched_from_tenable',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='low_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='medium_vuls',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='raw_summary_data',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='scan_run_uuid',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='scan_uuid',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='status_from_tenable',
        ),
        migrations.RemoveField(
            model_name='tenablescanlog',
            name='tenable_scan_id',
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='log_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='status',
            field=models.CharField(blank=True, help_text='Status of the scan.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='tenable_policy_identifier',
            field=models.CharField(blank=True, help_text="Identifier of the policy/template used (e.g., 'template-uuid' from scan creation 'uuid' field).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='tenable_scan_definition_id',
            field=models.IntegerField(blank=True, help_text="Numeric ID of the scan definition in Tenable (the 'id' field from scan creation).", null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='tenable_scan_run_uuid',
            field=models.UUIDField(blank=True, help_text="UUID of the launched scan instance/history in Tenable (the 'scan_uuid' or 'history_uuid' from launch).", null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenablescanlog',
            name='scan_name',
            field=models.CharField(blank=True, help_text='Name of the scan in Tenable.', max_length=255, null=True),
        ),
    ]
