# Generated by Django 5.2 on 2025-05-16 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_alter_tenablescanlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenableScanResultSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assets_scanned', models.IntegerField(blank=True, help_text='Number of assets scanned.', null=True)),
                ('scan_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the scan completed in Tenable.', null=True)),
                ('critical_vulnerabilities', models.IntegerField(default=0, help_text='Count of critical vulnerabilities found.')),
                ('high_vulnerabilities', models.IntegerField(default=0, help_text='Count of high vulnerabilities found.')),
                ('medium_vulnerabilities', models.IntegerField(default=0, help_text='Count of medium vulnerabilities found.')),
                ('low_vulnerabilities', models.IntegerField(default=0, help_text='Count of low vulnerabilities found.')),
                ('info_findings', models.IntegerField(default=0, help_text='Count of informational findings.')),
                ('raw_summary_data_json', models.JSONField(blank=True, help_text='Raw summary data from Tenable API as JSON.', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this summary was fetched and recorded in our system.')),
                ('last_updated_from_tenable', models.DateTimeField(blank=True, help_text='When this summary was last updated based on Tenable data.', null=True)),
                ('scan_log', models.OneToOneField(help_text='The scan log entry this summary pertains to.', on_delete=django.db.models.deletion.CASCADE, related_name='result_summary', to='tracker.tenablescanlog')),
            ],
            options={
                'verbose_name': 'Tenable Scan Result Summary',
                'verbose_name_plural': 'Tenable Scan Result Summaries',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
