# Generated by Django 5.2 on 2025-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_assetscandatasnapshot_assetinstalledsoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenablescanlog',
            name='report_last_saved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the report was last fetched and saved.', null=True),
        ),
        migrations.AddField(
            model_name='tenablescanlog',
            name='saved_report_path',
            field=models.CharField(blank=True, help_text='Relative path to the saved JSON scan report within MEDIA_ROOT.', max_length=512, null=True),
        ),
    ]
