# Generated by Django 5.2 on 2025-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_tenablescanlog_report_last_saved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenablescanlog',
            name='data_parsed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when scan data was last parsed into detailed asset models.', null=True),
        ),
    ]
