# Generated by Django 5.2 on 2025-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_tenablescanlog_data_parsed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Primary Contact Email'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary Contact Name'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Primary Contact Phone'),
        ),
    ]
