# Generated by Django 5.2 on 2025-05-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('release_notes', models.URLField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('engine_version', models.CharField(max_length=50)),
                ('manually_added', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentExtractedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_by', models.CharField(blank=True, max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('organisation_name', models.CharField(blank=True, max_length=255)),
                ('organisation_number', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('town_city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website_address', models.URLField(blank=True, max_length=255)),
                ('ce_renewal', models.BooleanField(default=False)),
                ('assessment_scope_whole_company', models.BooleanField(default=False)),
                ('enduser_devices', models.TextField(blank=True)),
                ('thin_client_devices', models.TextField(blank=True)),
                ('server_devices', models.TextField(blank=True)),
                ('mobile_devices', models.TextField(blank=True)),
                ('networks', models.TextField(blank=True)),
                ('number_of_home_workers', models.IntegerField(blank=True, null=True)),
                ('network_equipment', models.TextField(blank=True)),
                ('cloud_services', models.TextField(blank=True, help_text='Comma-separated list')),
                ('internet_browsers', models.TextField(blank=True, help_text='Comma-separated list')),
                ('malware_protection', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_details', to='tracker.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Extracted Detail',
                'verbose_name_plural': 'Assessment Extracted Details',
            },
        ),
    ]
