# Generated by Django 5.2 on 2025-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_browser_assessmentextracteddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='card_template_path',
            field=models.CharField(blank=True, help_text="Path to the HTML partial for this step's card on the assessment detail page, e.g., 'tracker/partials/client_scope_summary.html'", max_length=255, null=True, verbose_name='Card Template Path'),
        ),
    ]
