# Generated by Django 5.2 on 2025-05-25 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, help_text='Contact email for this person (optional).', max_length=254, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Work Phone Number')),
                ('mobile_number', models.CharField(blank=True, max_length=30, verbose_name='Mobile Phone Number')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department / Team')),
                ('role_in_assessment', models.CharField(help_text="e.g., Primary Technical Contact, System Administrator for 'Server X', End-user for testing", max_length=150, verbose_name='Role in Assessment Context')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_assessment_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Added By (Platform User)')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_contacts', to='tracker.assessment', verbose_name='Assessment')),
            ],
            options={
                'verbose_name': 'Assessment Personnel Contact',
                'verbose_name_plural': 'Assessment Personnel Contacts',
                'ordering': ['assessment', 'full_name'],
                'unique_together': {('assessment', 'full_name', 'role_in_assessment')},
            },
        ),
    ]
