# Generated by Django 5.2 on 2025-05-25 21:03

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_personnelsecuritytest_personnelcloudserviceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelcloudserviceaccess',
            name='personnel_mfa_proof',
            field=models.FileField(blank=True, help_text='Optional: Screenshot or file proving MFA is active for this person on this service.', null=True, upload_to=tracker.models.personnel_mfa_proof_upload_path, verbose_name='Personnel MFA Proof Screenshot'),
        ),
    ]
